# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import smdbrpc_pb2 as smdbrpc__pb2


class HotshardGatewayStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ContactHotshard = channel.unary_unary(
                '/smdbrpc.HotshardGateway/ContactHotshard',
                request_serializer=smdbrpc__pb2.HotshardRequest.SerializeToString,
                response_deserializer=smdbrpc__pb2.HotshardReply.FromString,
                )


class HotshardGatewayServicer(object):
    """The greeting service definition.
    """

    def ContactHotshard(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HotshardGatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ContactHotshard': grpc.unary_unary_rpc_method_handler(
                    servicer.ContactHotshard,
                    request_deserializer=smdbrpc__pb2.HotshardRequest.FromString,
                    response_serializer=smdbrpc__pb2.HotshardReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smdbrpc.HotshardGateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class HotshardGateway(object):
    """The greeting service definition.
    """

    @staticmethod
    def ContactHotshard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/smdbrpc.HotshardGateway/ContactHotshard',
            smdbrpc__pb2.HotshardRequest.SerializeToString,
            smdbrpc__pb2.HotshardReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
