# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smdbrpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smdbrpc.proto',
  package='smdbrpc',
  syntax='proto2',
  serialized_options=b'Z\013execinfrapb',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rsmdbrpc.proto\x12\x07smdbrpc\"5\n\x0cHLCTimestamp\x12\x10\n\x08walltime\x18\x01 \x01(\x03\x12\x13\n\x0blogicaltime\x18\x02 \x01(\x05\"$\n\x06KVPair\x12\x0b\n\x03key\x18\x01 \x01(\x04\x12\r\n\x05value\x18\x02 \x01(\x04\"z\n\x0fHotshardRequest\x12+\n\x0chlctimestamp\x18\x01 \x01(\x0b\x32\x15.smdbrpc.HLCTimestamp\x12%\n\x0cwrite_keyset\x18\x02 \x03(\x0b\x32\x0f.smdbrpc.KVPair\x12\x13\n\x0bread_keyset\x18\x03 \x03(\x04\"M\n\rHotshardReply\x12\x14\n\x0cis_committed\x18\x01 \x01(\x08\x12&\n\rread_valueset\x18\x02 \x03(\x0b\x32\x0f.smdbrpc.KVPair2X\n\x0fHotshardGateway\x12\x45\n\x0f\x43ontactHotshard\x12\x18.smdbrpc.HotshardRequest\x1a\x16.smdbrpc.HotshardReply\"\x00\x42\rZ\x0b\x65xecinfrapb'
)




_HLCTIMESTAMP = _descriptor.Descriptor(
  name='HLCTimestamp',
  full_name='smdbrpc.HLCTimestamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='walltime', full_name='smdbrpc.HLCTimestamp.walltime', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='logicaltime', full_name='smdbrpc.HLCTimestamp.logicaltime', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=79,
)


_KVPAIR = _descriptor.Descriptor(
  name='KVPair',
  full_name='smdbrpc.KVPair',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='smdbrpc.KVPair.key', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='smdbrpc.KVPair.value', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=117,
)


_HOTSHARDREQUEST = _descriptor.Descriptor(
  name='HotshardRequest',
  full_name='smdbrpc.HotshardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='hlctimestamp', full_name='smdbrpc.HotshardRequest.hlctimestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='write_keyset', full_name='smdbrpc.HotshardRequest.write_keyset', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read_keyset', full_name='smdbrpc.HotshardRequest.read_keyset', index=2,
      number=3, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=241,
)


_HOTSHARDREPLY = _descriptor.Descriptor(
  name='HotshardReply',
  full_name='smdbrpc.HotshardReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_committed', full_name='smdbrpc.HotshardReply.is_committed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='read_valueset', full_name='smdbrpc.HotshardReply.read_valueset', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=320,
)

_HOTSHARDREQUEST.fields_by_name['hlctimestamp'].message_type = _HLCTIMESTAMP
_HOTSHARDREQUEST.fields_by_name['write_keyset'].message_type = _KVPAIR
_HOTSHARDREPLY.fields_by_name['read_valueset'].message_type = _KVPAIR
DESCRIPTOR.message_types_by_name['HLCTimestamp'] = _HLCTIMESTAMP
DESCRIPTOR.message_types_by_name['KVPair'] = _KVPAIR
DESCRIPTOR.message_types_by_name['HotshardRequest'] = _HOTSHARDREQUEST
DESCRIPTOR.message_types_by_name['HotshardReply'] = _HOTSHARDREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

HLCTimestamp = _reflection.GeneratedProtocolMessageType('HLCTimestamp', (_message.Message,), {
  'DESCRIPTOR' : _HLCTIMESTAMP,
  '__module__' : 'smdbrpc_pb2'
  # @@protoc_insertion_point(class_scope:smdbrpc.HLCTimestamp)
  })
_sym_db.RegisterMessage(HLCTimestamp)

KVPair = _reflection.GeneratedProtocolMessageType('KVPair', (_message.Message,), {
  'DESCRIPTOR' : _KVPAIR,
  '__module__' : 'smdbrpc_pb2'
  # @@protoc_insertion_point(class_scope:smdbrpc.KVPair)
  })
_sym_db.RegisterMessage(KVPair)

HotshardRequest = _reflection.GeneratedProtocolMessageType('HotshardRequest', (_message.Message,), {
  'DESCRIPTOR' : _HOTSHARDREQUEST,
  '__module__' : 'smdbrpc_pb2'
  # @@protoc_insertion_point(class_scope:smdbrpc.HotshardRequest)
  })
_sym_db.RegisterMessage(HotshardRequest)

HotshardReply = _reflection.GeneratedProtocolMessageType('HotshardReply', (_message.Message,), {
  'DESCRIPTOR' : _HOTSHARDREPLY,
  '__module__' : 'smdbrpc_pb2'
  # @@protoc_insertion_point(class_scope:smdbrpc.HotshardReply)
  })
_sym_db.RegisterMessage(HotshardReply)


DESCRIPTOR._options = None

_HOTSHARDGATEWAY = _descriptor.ServiceDescriptor(
  name='HotshardGateway',
  full_name='smdbrpc.HotshardGateway',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=322,
  serialized_end=410,
  methods=[
  _descriptor.MethodDescriptor(
    name='ContactHotshard',
    full_name='smdbrpc.HotshardGateway.ContactHotshard',
    index=0,
    containing_service=None,
    input_type=_HOTSHARDREQUEST,
    output_type=_HOTSHARDREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_HOTSHARDGATEWAY)

DESCRIPTOR.services_by_name['HotshardGateway'] = _HOTSHARDGATEWAY

# @@protoc_insertion_point(module_scope)
